### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ianhom** [ELE-Clouds/Programmable-Line-Detector#1]
Hi, it seems a great project! May I ask what kind of platform or MCU will be used?

**Comment by ELE-Clouds** [comment]
@ianhom 硬件部分待定，MCU程序部分代码部分尽量做到兼容目前大多数MCU。方便移植和扩展功能。

**Comment by ianhom** [comment]
So you want portable program,  Hardware Abstract Layer may be a good choice

**Comment by ELE-Clouds** [comment]
考虑当前意见。
